export const CONTENT_STORAGE_KEY = 'atc-site-content-v1'
export const CONTENT_UPDATED_EVENT = 'atc-content-updated'

export const CONTENT_SECTIONS = [
  { key: 'brand', label: 'Brand System', description: 'Logos, club name, institution details, and shared brand text.' },
  { key: 'nav', label: 'Navigation', description: 'Header and footer links shown across the website.' },
  { key: 'loading', label: 'Loading Screen', description: 'Intro animation text and loading wordmark.' },
  { key: 'hero', label: 'Hero', description: 'Main landing section, headline, description, and call-to-action buttons.' },
  { key: 'about', label: 'About', description: 'Club story, statistics, pillars, and NIAT badge.' },
  { key: 'whyJoin', label: 'Why Join', description: 'Benefits and membership value cards.' },
  { key: 'domains', label: 'Domains', description: 'Technical focus areas and feature chips.' },
  { key: 'events', label: 'Events', description: 'Upcoming and past event listings with registration links.' },
  { key: 'leadership', label: 'Leadership', description: 'Team members, roles, bios, and leadership CTA.' },
  { key: 'gallery', label: 'Gallery', description: 'Gallery images, captions, aspect ratios, and fallback colors.' },
  { key: 'achievements', label: 'Achievements', description: 'Impact stats, milestones, and timeline content.' },
  { key: 'vision', label: 'Vision', description: 'Vision quote, attribution, and value chips.' },
  { key: 'contact', label: 'Contact', description: 'Join banner, email, Instagram, and contact card text.' },
  { key: 'footer', label: 'Footer', description: 'Footer description, labels, CTA, and copyright copy.' },
]

export const DEFAULT_CONTENT = {
  brand: {
    name: 'Advanced Tech Club',
    shortName: 'ATC',
    institution: 'NxtWave Institute of Advanced Technologies',
    institutionShort: 'NxtWave NIAT',
    city: 'Hyderabad',
    logo: '/atc-logo.jpg',
    institutionLogo: '/niat-logo.png',
    tagline: 'Innovating Tomorrow Through Robotics & IoT',
    description: 'A student-led Robotics & IoT innovation community at NxtWave Institute of Advanced Technologies, Hyderabad.',
  },
  nav: {
    links: [
      { label: 'About', href: '#about' },
      { label: 'Domains', href: '#domains' },
      { label: 'Events', href: '#events' },
      { label: 'Team', href: '#leadership' },
      { label: 'Gallery', href: '#gallery' },
      { label: 'Achievements', href: '#achievements' },
      { label: 'Contact', href: '#contact' },
    ],
  },
  loading: {
    institutionText: 'NxtWave Institute of Advanced Technologies',
    title: 'ADVANCED TECH CLUB',
    tagline: 'Innovating Tomorrow Through Robotics & IoT',
  },
  hero: {
    eyebrow: 'A Robotics & IoT Club of NxtWave Institute of Advanced Technologies',
    titleLine1: 'ADVANCED',
    titleLine2: 'TECH CLUB',
    tagline: 'Innovating Tomorrow Through Robotics & IoT',
    description: 'Building the next generation of innovators through hands-on workshops, collaborative learning, and emerging technologies.',
    primaryButton: 'Explore Events',
    secondaryButton: 'Join Us',
    scrollLabel: 'Scroll',
  },
  about: {
    eyebrow: 'About the Club',
    titlePrefix: 'About',
    titleHighlight: 'Advanced',
    titleSuffix: 'Tech Club',
    paragraphs: [
      'Advanced Tech Club is a student-led innovation community at NIAT focused on Robotics and IoT. We are a space where curiosity becomes capability, and prototypes become products.',
      'We empower students through practical learning, technical workshops, collaborative projects, and real-world problem solving - bridging the gap between classroom theory and industry practice.',
      'From building autonomous robots to designing sensor networks that talk to the cloud, ATC is where the next generation of engineers take their first real steps.',
    ],
    primaryButton: 'Become a Member',
    secondaryButton: 'Explore Domains ->',
    stats: [
      { icon: 'Users', value: '200+', label: 'Members' },
      { icon: 'Target', value: '15+', label: 'Workshops' },
      { icon: 'Lightbulb', value: '8+', label: 'Projects' },
      { icon: 'Trophy', value: '3+', label: 'Awards' },
    ],
    pillars: [
      { title: 'Practical Focus', desc: 'Real hardware, real code, real solutions - not just theory.' },
      { title: 'Community-Driven', desc: 'Peer learning, mentorship, and collaboration at every level.' },
      { title: 'Industry-Aligned', desc: 'Skills aligned with what robotics & IoT companies actually need.' },
    ],
    badge: {
      label: 'Est. 2024',
      text: 'NIAT - Hyderabad',
    },
  },
  whyJoin: {
    eyebrow: 'Why Join Us',
    titlePrefix: 'Everything you need to',
    titleHighlight: 'excel',
    titleSuffix: '',
    description: 'ATC gives you the resources, the community, and the environment to grow from curious student to confident engineer.',
    cards: [
      {
        icon: 'Wrench',
        title: 'Hands-On Learning',
        description: 'Get your hands on real hardware: microcontrollers, sensors, servo motors, and PCBs. Every concept is backed by a working prototype.',
        accent: 'Build. Break. Learn.',
      },
      {
        icon: 'BrainCircuit',
        title: 'Industry-Relevant Skills',
        description: 'Master the tools that matter - embedded C, Python, MQTT, ROS, CAD design, and cloud IoT platforms used in the real industry.',
        accent: 'Skills that hire.',
      },
      {
        icon: 'Handshake',
        title: 'Innovation & Collaboration',
        description: 'Work in cross-functional teams, pitch ideas in ideathons, and co-build projects that solve problems beyond the classroom.',
        accent: 'Ideas meet execution.',
      },
      {
        icon: 'Star',
        title: 'Leadership Opportunities',
        description: 'Lead workshops, head projects, represent ATC at events. The club is a fast track for developing confidence and technical authority.',
        accent: 'Your platform to lead.',
      },
    ],
  },
  domains: {
    eyebrow: 'Our Domains',
    titlePrefix: 'Two pillars of',
    titleHighlight: 'innovation',
    titleSuffix: '',
    description: 'Our technical focus spans two of the most transformative fields in modern engineering.',
    ctaLabel: 'Explore workshops',
    items: [
      {
        icon: 'Bot',
        label: 'Domain 01',
        title: 'Robotics',
        subtitle: 'Building Intelligent Machines',
        description: 'Design, build, and program autonomous robots and automation systems. From servo-driven arms to obstacle-navigating bots, we tackle real engineering challenges.',
        features: [
          'Autonomous Navigation',
          'Embedded Programming',
          'Mechanical Design & CAD',
          'Computer Vision',
          'ROS Framework',
        ],
        color: '#DC2626',
      },
      {
        icon: 'Wifi',
        label: 'Domain 02',
        title: 'Internet of Things',
        subtitle: 'Connecting the Physical World',
        description: 'Create intelligent sensor networks, cloud-connected devices, and smart systems that bridge the physical and digital world for real-world applications.',
        features: [
          'ESP32 & Raspberry Pi',
          'MQTT & Cloud Integration',
          'Sensor Fusion',
          'Real-Time Dashboards',
          'Edge Computing',
        ],
        color: '#991B1B',
      },
    ],
  },
  events: {
    eyebrow: 'Events & Workshops',
    titlePrefix: 'Where learning',
    titleHighlight: 'happens',
    titleSuffix: '',
    description: "Hands-on workshops, competitive challenges, and community hackathons - there's always something building at ATC.",
    tabs: {
      upcoming: 'Upcoming',
      past: 'Past Events',
    },
    statusLabels: {
      upcoming: 'Upcoming',
      completed: 'Completed',
    },
    registerLabel: 'Register Now',
    ctaPrompt: 'Want to be notified about future events?',
    ctaButton: 'Join the Community',
    categoryColors: {
      Competition: '#DC2626',
      Workshop: '#B91C1C',
      Hackathon: '#991B1B',
      Orientation: '#7F1D1D',
    },
    upcoming: [
      {
        id: 1,
        name: 'RoboBlitz 2025',
        date: 'August 15, 2025',
        category: 'Competition',
        description: 'Annual robotics challenge where teams design and program autonomous bots to navigate obstacle courses under strict time limits.',
        registrationLink: '#',
        tag: 'Upcoming',
      },
      {
        id: 2,
        name: 'IoT Bootcamp',
        date: 'September 3-5, 2025',
        category: 'Workshop',
        description: 'A 3-day intensive workshop covering ESP32, sensor integration, MQTT protocol, and building real-time IoT dashboards from scratch.',
        registrationLink: '#',
        tag: 'Upcoming',
      },
      {
        id: 3,
        name: 'Hackathon: Build the Future',
        date: 'October 12, 2025',
        category: 'Hackathon',
        description: '24-hour hackathon challenging participants to prototype tech solutions for real-world urban problems using robotics and IoT.',
        registrationLink: '#',
        tag: 'Upcoming',
      },
    ],
    past: [
      {
        id: 4,
        name: 'Circuit Slam 1.0',
        date: 'January 20, 2025',
        category: 'Workshop',
        description: 'Introductory hardware workshop covering PCB design, soldering, and basic circuit theory with hands-on projects for 60+ attendees.',
        tag: 'Past',
      },
      {
        id: 5,
        name: 'Tech Orientation 2025',
        date: 'February 8, 2025',
        category: 'Orientation',
        description: "Annual club induction event introducing new members to ATC's vision, ongoing projects, mentorship structure, and upcoming roadmap.",
        tag: 'Past',
      },
      {
        id: 6,
        name: 'Arduino Zero to Hero',
        date: 'March 15, 2025',
        category: 'Workshop',
        description: 'Hands-on Arduino programming workshop from absolute basics to building a smart home prototype - participated by 80+ students.',
        tag: 'Past',
      },
    ],
  },
  leadership: {
    eyebrow: 'Leadership Team',
    titlePrefix: 'The people',
    titleHighlight: 'driving',
    titleSuffix: 'ATC',
    description: 'A team of passionate students committed to building a premier innovation community at NIAT.',
    ctaPrompt: 'Interested in joining the leadership team next cycle?',
    ctaButton: 'Get Involved',
    roleColors: {
      President: { bg: 'rgba(220,38,38,0.15)', border: 'rgba(220,38,38,0.35)', text: '#DC2626' },
      'Vice President': { bg: 'rgba(185,28,28,0.12)', border: 'rgba(185,28,28,0.3)', text: '#B91C1C' },
      'Operations Head': { bg: 'rgba(153,27,27,0.12)', border: 'rgba(153,27,27,0.3)', text: '#991B1B' },
      'Finance Head': { bg: 'rgba(127,29,29,0.12)', border: 'rgba(127,29,29,0.3)', text: '#9B1C1C' },
      'Outreach Head': { bg: 'rgba(185,28,28,0.12)', border: 'rgba(185,28,28,0.3)', text: '#B91C1C' },
      'Creative & Design Head': { bg: 'rgba(220,38,38,0.12)', border: 'rgba(220,38,38,0.28)', text: '#DC2626' },
      'Social Media Head': { bg: 'rgba(153,27,27,0.12)', border: 'rgba(153,27,27,0.3)', text: '#991B1B' },
    },
    team: [
      {
        name: 'Richandel',
        role: 'President',
        initials: 'RC',
        bio: "Driving vision and strategy for Advanced Tech Club's growth and innovation.",
      },
      {
        name: 'Deekshith',
        role: 'Vice President',
        initials: 'DK',
        bio: 'Supporting operations and bridging team collaboration across all domains.',
      },
      {
        name: 'Vedasri',
        role: 'Operations Head',
        initials: 'VS',
        bio: 'Orchestrating seamless execution of events, workshops, and club activities.',
      },
      {
        name: 'Narendra',
        role: 'Finance Head',
        initials: 'NR',
        bio: 'Managing club finances and ensuring sustainable resource allocation.',
      },
      {
        name: 'Tanisha',
        role: 'Outreach Head',
        initials: 'TN',
        bio: "Building partnerships and expanding the club's reach across communities.",
      },
      {
        name: 'Ayush',
        role: 'Creative & Design Head',
        initials: 'AY',
        bio: "Shaping the visual identity and creative direction of ATC's brand.",
      },
      {
        name: 'Tanmay',
        role: 'Social Media Head',
        initials: 'TM',
        bio: "Amplifying ATC's presence and story across digital platforms.",
      },
    ],
  },
  gallery: {
    eyebrow: 'Gallery',
    titlePrefix: 'Moments from the',
    titleHighlight: 'lab',
    titleSuffix: '',
    description: 'A glimpse into workshops, builds, hackathons, and the everyday magic of ATC.',
    note: 'More photos coming soon - follow us on Instagram for real-time updates.',
    attribution: 'Advanced Tech Club - NIAT',
    items: [
      { id: 1, aspect: 'tall', label: 'Robotics Workshop 2025', hue: '220,38,38', src: '/img1.png' },
      { id: 2, aspect: 'wide', label: 'Circuit Slam 1.0', hue: '153,27,27', src: '/photo2.png' },
      { id: 3, aspect: 'square', label: 'IoT Bootcamp Setup', hue: '185,28,28', src: '/photo3.png' },
      { id: 4, aspect: 'tall', label: 'Team Collaboration', hue: '220,38,38', src: '/img4.png' },
      { id: 5, aspect: 'square', label: 'Arduino Session', hue: '127,29,29', src: '/photo5.png' },
      { id: 6, aspect: 'wide', label: 'Tech Orientation 2025', hue: '153,27,27', src: '/img6.png' },
      { id: 7, aspect: 'square', label: 'Project Demo Day', hue: '185,28,28', src: '' },
      { id: 8, aspect: 'tall', label: 'Hackathon Highlights', hue: '220,38,38', src: '' },
      { id: 9, aspect: 'wide', label: 'RoboBlitz 2024 Finals', hue: '127,29,29', src: '' },
    ],
  },
  achievements: {
    eyebrow: 'Achievements',
    titlePrefix: 'Milestones &',
    titleHighlight: 'impact',
    titleSuffix: '',
    description: 'From founding to our first awards - a snapshot of what ATC has built in a short time.',
    timelineTitlePrefix: 'Our',
    timelineTitleHighlight: 'Story',
    timelineTitleSuffix: 'So Far',
    stats: [
      { icon: 'Users', value: 200, suffix: '+', label: 'Active Members' },
      { icon: 'BookOpen', value: 15, suffix: '+', label: 'Workshops Hosted' },
      { icon: 'Rocket', value: 8, suffix: '+', label: 'Projects Deployed' },
      { icon: 'Trophy', value: 3, suffix: '+', label: 'Awards Won' },
    ],
    milestones: [
      {
        year: '2024',
        title: 'Club Founded',
        description: 'Advanced Tech Club established at NIAT with a founding cohort of 40 passionate students.',
      },
      {
        year: '2024',
        title: 'First Robotics Workshop',
        description: 'Hosted a 2-day robotics workshop attracting 100+ participants from across departments.',
      },
      {
        year: '2025',
        title: 'IoT Lab Partnership',
        description: 'Secured access to a dedicated IoT prototyping lab with industry-grade equipment.',
      },
      {
        year: '2025',
        title: 'Regional Recognition',
        description: 'ATC projects showcased at regional tech fest, winning Best Innovation Award.',
      },
      {
        year: '2025',
        title: '200+ Member Community',
        description: 'Grew to a 200+ member community with structured mentorship and project tracks.',
      },
    ],
  },
  vision: {
    eyebrow: 'Our Vision',
    quoteStart: 'To become the leading student innovation community at NIAT, inspiring future engineers and technologists to solve',
    quoteHighlight: 'real-world challenges',
    quoteEnd: 'through Robotics and IoT.',
    attribution: 'Advanced Tech Club - NIAT',
    coreValues: ['Build', 'Innovate', 'Lead', 'Impact', 'Collaborate'],
  },
  contact: {
    eyebrow: 'Join the Community',
    headingStart: 'Ready to innovate,',
    headingHighlight: 'build',
    headingEnd: 'and lead the future?',
    description: 'Join Advanced Tech Club today. Be part of a community building real things, solving real problems, and growing fast.',
    primaryButton: 'Email Us',
    secondaryButton: 'Follow on Instagram',
    emailLabel: 'Email',
    instagramLabel: 'Instagram',
    email: 'advancedtechclub.niatxcdu@gmail.com',
    instagram: 'https://www.instagram.com/adv_club_niatxcdu/',
    instagramHandle: '@adv_club_niatxcdu',
    emailSubject: 'Join Advanced Tech Club',
    emailBody: 'Hi Advanced Tech Club Team,\n\nI would like to join the club and learn more about membership. Please let me know the next steps.\n\nThanks,\n[Your Name]',
  },
  footer: {
    description: 'A student-led Robotics & IoT innovation community at NxtWave Institute of Advanced Technologies, Hyderabad.',
    quickLinksHeading: 'Quick Links',
    contactHeading: 'Contact',
    emailLabel: 'Email',
    institutionLabel: 'Institution',
    institutionDisplay: 'NxtWave Institute of\nAdvanced Technologies',
    ctaLabel: 'Join ATC Today',
    copyrightText: '(c) {year} Advanced Tech Club - NxtWave Institute of Advanced Technologies. All rights reserved.',
    builtWithPrefix: 'Built with',
    builtWithHighlight: 'heart',
    builtWithSuffix: 'by ATC members',
  },
}
